import os
from config_loader import get_agent_settings

_s = get_agent_settings()

# Network (read from env vars with defaults)
HOST = os.getenv("HOST", "0.0.0.0")
PORT = int(os.getenv("PORT", "8000"))
WS_UPDATE_INTERVAL = int(os.getenv("WS_UPDATE_INTERVAL", "2"))
RISK_TREND_MAX = int(os.getenv("RISK_TREND_MAX", "60"))
WS_URL = "/ws"
API_PREFIX = "/api"

# Data source label
DATA_SOURCE_LABEL = "simulated"
PLANT_NAME = "Visakhapatnam Steel Plant"

# API metadata
APP_TITLE = "ZeroHarm AI - Industrial Safety Intelligence Platform"
APP_VERSION = "1.0.0"
ALLOWED_ORIGINS = ["*"]

# Health index weights
HEALTH_INDEX_WEIGHTS = {"sensor": 0.25, "permit": 0.2, "risk": 0.3, "compliance": 0.25}
HEALTH_LABEL_EXCELLENT = 85
HEALTH_LABEL_GOOD = 70
HEALTH_LABEL_FAIR = 50
HEALTH_LABEL_EXCELLENT_STR = "Excellent"
HEALTH_LABEL_GOOD_STR = "Good"
HEALTH_LABEL_FAIR_STR = "Fair"
HEALTH_LABEL_POOR_STR = "Poor"
HIGH_RISK_PERMIT_PENALTY = float(os.getenv("HIGH_RISK_PERMIT_PENALTY", "0.15"))

# Sensor status strings
SENSOR_STATUS_NORMAL = "normal"
SENSOR_STATUS_WARNING = "warning"
SENSOR_STATUS_CRITICAL = "critical"
UNKNOWN_ZONE = "unknown"
UNKNOWN_LABEL = "Unknown"

# Severity values
SEVERITY_ORDER = {"catastrophic": 5, "critical": 4, "major": 3, "moderate": 2, "near_miss": 1}
SEVERITY_LABELS = {5: "CRITICAL", 4: "HIGH", 3: "MEDIUM", 2: "LOW", 1: "INFO"}
HIGH_RISK_LEVELS = {"Critical", "High"}

# Default values
DEFAULT_PERMIT_TYPE = "Hot Work"
DEFAULT_ZONE_HAZARD_CLASS = "High"
DEFAULT_TOP_K = int(os.getenv("RAG_DEFAULT_TOP_K", "3"))
DEFAULT_INCIDENT_TYPE = "gas_leak"
DEFAULT_EMERGENCY_TYPE = "medical_emergency"

# What-If Simulator defaults
SENSOR_DEFAULT_THRESHOLD = 20
SENSOR_DEFAULT_CRITICAL = 40
SIM_RISK_BONUS_ADDER = 0.2
SIM_PTW_ID_RANGE = (100, 999)
SIM_PTW_CUSTOM_ID_RANGE = (1000, 9999)
SIM_DEFAULT_ZONE = "Z01"
SIM_WORKER_NAME = "Simulation Operator"
SIM_CUSTOM_WORKER_NAME = "Scenario Operator"

# Activity feed
ACTIVITY_ID_PREFIX = "ACT-"
ACTIVITY_FEED_PAYLOAD_COUNT = 15
RISK_TREND_PAYLOAD_COUNT = 30

# Compliance
COMPLIANCE_AUDIT_INTERVAL = 3
MAX_COMPOUND_RISKS_TO_LOG = 2

# Export
DATA_SOURCE_LABEL_EXPORT = "simulated"

# Agent names
AGENT_SENSOR_MONITOR = "Sensor Monitor Agent"
AGENT_PERMIT_ACTIVITY = "Permit Activity Agent"
AGENT_MAINTENANCE_STATUS = "Maintenance Status Agent"
AGENT_COMPLIANCE = "Quality & Compliance Audit Agent"
AGENT_COMPOUND_RISK = "Compound Risk Detection Engine"
AGENT_EMERGENCY = "Emergency Response Orchestrator"
AGENT_WHAT_IF = "What-If Scenario Simulator"
AGENT_FUSION = "Risk Fusion Supervisor"
AGENT_SYSTEM = "ZeroHarm System"

# Recommendation titles
RECOMMENDATION_TEXTS = {
    "compliance_audit": "Schedule comprehensive safety audit within 7 days",
    "gas_detection_cal": "Review gas detection calibration schedule for extreme-hazard zones (Z01/Z02/Z07)",
    "simops_training": "Conduct SIMOPS training for all permit issuers",
    "emergency_drill": "Verify emergency drill schedule for current quarter",
    "loto_review": "Review LOTO procedures with maintenance team",
    "hot_work_lel": "IMMEDIATE SUSPENSION: Flammable atmosphere detected during hot work. Evacuate area and purge before any further work.",
    "confined_space_o2": "IMMEDIATE SUSPENSION: Unsafe oxygen level for confined space entry. Stop entry, ventilate area, and re-test atmosphere.",
    "h2s": "IMMEDIATE SUSPENSION: Toxic gas detected. Evacuate area. Respiratory protection required before any re-entry.",
    "default": "REVIEW REQUIRED: Multiple risk factors detected. Supervisor assessment needed before work continues.",
}

# Incident report
INCIDENT_REPORT_CLASSIFICATION = "CONFIDENTIAL - FOR REGULATORY SUBMISSION"
REPORTING_OFFICER_LABEL = "Auto-generated by ZeroHarm AI Emergency Response System"

# Compliance
OVERALL_COMPLIANCE_SCORE_KEY = "overall_compliance_score"
