import os
import logging
from config_loader import get_agent_settings

get_agent_settings()

# Logging
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()

# Network (read from env vars with defaults)
HOST = os.getenv("HOST", "0.0.0.0")
PORT = max(1, min(65535, int(os.getenv("PORT", "8000"))))
WS_UPDATE_INTERVAL = int(os.getenv("WS_UPDATE_INTERVAL", "2"))
RISK_TREND_MAX = int(os.getenv("RISK_TREND_MAX", "60"))
WS_URL = "/ws"
API_PREFIX = "/api"
MAX_WS_CONNECTIONS = int(os.getenv("MAX_WS_CONNECTIONS", "50"))
MAX_WS_MESSAGE_SIZE = int(os.getenv("MAX_WS_MESSAGE_SIZE", "65536"))

# Data source label
DATA_SOURCE_LABEL = "simulated"
PLANT_NAME = "Visakhapatnam Steel Plant"

# API metadata
APP_TITLE = "ZeroHarm AI - Industrial Safety Intelligence Platform"
APP_VERSION = "1.0.0"
_DEFAULT_ORIGINS = "http://localhost:3000,http://localhost:8080"
ALLOWED_ORIGINS = os.getenv("ALLOWED_ORIGINS", _DEFAULT_ORIGINS).split(",")

# Security
API_KEY = os.getenv("API_KEY", "")
RATE_LIMIT_REQUESTS = int(os.getenv("RATE_LIMIT_REQUESTS", "100"))
RATE_LIMIT_WINDOW = int(os.getenv("RATE_LIMIT_WINDOW", "60"))

# Health index weights
HEALTH_INDEX_WEIGHTS = {"sensor": 0.25, "permit": 0.2, "risk": 0.3, "compliance": 0.25}
HEALTH_LABEL_EXCELLENT = 85
HEALTH_LABEL_GOOD = 70
HEALTH_LABEL_FAIR = 50
HEALTH_LABEL_EXCELLENT_STR = "Excellent"
HEALTH_LABEL_GOOD_STR = "Good"
HEALTH_LABEL_FAIR_STR = "Fair"
HEALTH_LABEL_POOR_STR = "Poor"
HIGH_RISK_PERMIT_PENALTY = float(os.getenv("HIGH_RISK_PERMIT_PENALTY", "0.15"))

# Sensor status strings
SENSOR_STATUS_NORMAL = "normal"
SENSOR_STATUS_WARNING = "warning"
SENSOR_STATUS_CRITICAL = "critical"
UNKNOWN_ZONE = "plant"
UNKNOWN_LABEL = "Unknown"

# Severity values — runtime severity strings (all lowercase)
SEVERITY_NORMAL = "normal"
SEVERITY_WARNING = "warning"
SEVERITY_CRITICAL = "critical"
SEVERITY_HIGH = "high"
SEVERITY_MEDIUM = "medium"
SEVERITY_LOW = "low"
SEVERITY_INFO = "info"
SEVERITY_PASSED = "passed"

# Severity mapping for internal risk level weights (different from runtime display)
HIGH_RISK_LEVELS = {"critical", "high"}

# Default values
DEFAULT_PERMIT_TYPE = "Hot Work"
DEFAULT_ZONE_HAZARD_CLASS = "High"
DEFAULT_TOP_K = int(os.getenv("RAG_DEFAULT_TOP_K", "3"))
DEFAULT_INCIDENT_TYPE = "gas_leak"
DEFAULT_EMERGENCY_TYPE = "medical_emergency"

# What-If Simulator defaults
SENSOR_DEFAULT_THRESHOLD = 20
SENSOR_DEFAULT_CRITICAL = 40
SIM_RISK_BONUS_ADDER = 0.2
SIM_PTW_ID_RANGE = (100, 999)
SIM_PTW_CUSTOM_ID_RANGE = (1000, 9999)
SIM_DEFAULT_ZONE = "Z01"
SIM_WORKER_NAME = "Simulation Operator"
SIM_CUSTOM_WORKER_NAME = "Scenario Operator"

# Activity feed
ACTIVITY_ID_PREFIX = "ACT-"
ACTIVITY_FEED_PAYLOAD_COUNT = 15
RISK_TREND_PAYLOAD_COUNT = 30

# Database
DATABASE_URL = os.getenv("DATABASE_URL", "sqlite+aiosqlite:///zeroharm.db")

# Compliance
COMPLIANCE_AUDIT_INTERVAL = 3
MAX_COMPOUND_RISKS_TO_LOG = 2

# Export
DATA_SOURCE_LABEL_EXPORT = "simulated"

# Agent names
AGENT_SENSOR_MONITOR = "Sensor Monitor Agent"
AGENT_PERMIT_ACTIVITY = "Permit Activity Agent"
AGENT_MAINTENANCE_STATUS = "Maintenance Status Agent"
AGENT_COMPLIANCE = "Quality & Compliance Audit Agent"
AGENT_COMPOUND_RISK = "Compound Risk Detection Engine"
AGENT_EMERGENCY = "Emergency Response Orchestrator"
AGENT_WHAT_IF = "What-If Scenario Simulator"
AGENT_FUSION = "Risk Fusion Supervisor"
AGENT_SYSTEM = "ZeroHarm System"

# Recommendation titles
RECOMMENDATION_TEXTS = {
    "compliance_audit": "Schedule comprehensive safety audit within 7 days",
    "gas_detection_cal": "Review gas detection calibration schedule for extreme-hazard zones (Z01/Z02/Z07)",
    "simops_training": "Conduct SIMOPS training for all permit issuers",
    "emergency_drill": "Verify emergency drill schedule for current quarter",
    "loto_review": "Review LOTO procedures with maintenance team",
    "hot_work_lel": "IMMEDIATE SUSPENSION: Flammable atmosphere detected during hot work. Evacuate area and purge before any further work.",
    "confined_space_o2": "IMMEDIATE SUSPENSION: Unsafe oxygen level for confined space entry. Stop entry, ventilate area, and re-test atmosphere.",
    "h2s": "IMMEDIATE SUSPENSION: Toxic gas detected. Evacuate area. Respiratory protection required before any re-entry.",
    "default": "REVIEW REQUIRED: Multiple risk factors detected. Supervisor assessment needed before work continues.",
}

# Incident report
INCIDENT_REPORT_CLASSIFICATION = "CONFIDENTIAL - FOR REGULATORY SUBMISSION"
REPORTING_OFFICER_LABEL = "Auto-generated by ZeroHarm AI Emergency Response System"

# Compliance
OVERALL_COMPLIANCE_SCORE_KEY = "overall_compliance_score"

# Vision / camera
CAMERA_RTSP_URL = os.getenv("CAMERA_RTSP_URL", "")
CAMERA_CHECK_INTERVAL = int(os.getenv("CAMERA_CHECK_INTERVAL", "5"))
VISION_MODEL_PATH = os.getenv("VISION_MODEL_PATH", "yolov8n.pt")
VISION_ENABLED = os.getenv("VISION_ENABLED", "false").lower() == "true"

# JWT
JWT_SECRET = os.getenv("JWT_SECRET", "zeroharm-default-secret-change-in-production")
JWT_EXPIRY_HOURS = int(os.getenv("JWT_EXPIRY_HOURS", "24"))

# Alert channel env vars
SLACK_WEBHOOK_URL = os.getenv("SLACK_WEBHOOK_URL", "")
SMTP_SERVER = os.getenv("SMTP_SERVER", "")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USER = os.getenv("SMTP_USER", "")
SMTP_PASS = os.getenv("SMTP_PASS", "")
ALERT_EMAIL_TO = os.getenv("ALERT_EMAIL_TO", "")
TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "")
TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "")
TWILIO_FROM = os.getenv("TWILIO_FROM", "")
ALERT_SMS_TO = os.getenv("ALERT_SMS_TO", "")
